# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/d/dev/work/sgdtk-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/d/dev/work/sgdtk-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/d/dev/work/sgdtk-cpp/CMakeFiles /cygdrive/d/dev/work/sgdtk-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/d/dev/work/sgdtk-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Train

# Build rule for target.
Train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Train
.PHONY : Train

# fast build rule for target.
Train/fast:
	$(MAKE) -f CMakeFiles/Train.dir/build.make CMakeFiles/Train.dir/build
.PHONY : Train/fast

#=============================================================================
# Target rules for targets named sgdtk

# Build rule for target.
sgdtk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sgdtk
.PHONY : sgdtk

# fast build rule for target.
sgdtk/fast:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/build
.PHONY : sgdtk/fast

Train.o: Train.cpp.o

.PHONY : Train.o

# target to build an object file
Train.cpp.o:
	$(MAKE) -f CMakeFiles/Train.dir/build.make CMakeFiles/Train.dir/Train.cpp.o
.PHONY : Train.cpp.o

Train.i: Train.cpp.i

.PHONY : Train.i

# target to preprocess a source file
Train.cpp.i:
	$(MAKE) -f CMakeFiles/Train.dir/build.make CMakeFiles/Train.dir/Train.cpp.i
.PHONY : Train.cpp.i

Train.s: Train.cpp.s

.PHONY : Train.s

# target to generate assembly for a file
Train.cpp.s:
	$(MAKE) -f CMakeFiles/Train.dir/build.make CMakeFiles/Train.dir/Train.cpp.s
.PHONY : Train.cpp.s

src/DenseVectorN.o: src/DenseVectorN.cpp.o

.PHONY : src/DenseVectorN.o

# target to build an object file
src/DenseVectorN.cpp.o:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/DenseVectorN.cpp.o
.PHONY : src/DenseVectorN.cpp.o

src/DenseVectorN.i: src/DenseVectorN.cpp.i

.PHONY : src/DenseVectorN.i

# target to preprocess a source file
src/DenseVectorN.cpp.i:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/DenseVectorN.cpp.i
.PHONY : src/DenseVectorN.cpp.i

src/DenseVectorN.s: src/DenseVectorN.cpp.s

.PHONY : src/DenseVectorN.s

# target to generate assembly for a file
src/DenseVectorN.cpp.s:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/DenseVectorN.cpp.s
.PHONY : src/DenseVectorN.cpp.s

src/Exception.o: src/Exception.cpp.o

.PHONY : src/Exception.o

# target to build an object file
src/Exception.cpp.o:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/Exception.cpp.o
.PHONY : src/Exception.cpp.o

src/Exception.i: src/Exception.cpp.i

.PHONY : src/Exception.i

# target to preprocess a source file
src/Exception.cpp.i:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/Exception.cpp.i
.PHONY : src/Exception.cpp.i

src/Exception.s: src/Exception.cpp.s

.PHONY : src/Exception.s

# target to generate assembly for a file
src/Exception.cpp.s:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/Exception.cpp.s
.PHONY : src/Exception.cpp.s

src/LinearModel.o: src/LinearModel.cpp.o

.PHONY : src/LinearModel.o

# target to build an object file
src/LinearModel.cpp.o:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/LinearModel.cpp.o
.PHONY : src/LinearModel.cpp.o

src/LinearModel.i: src/LinearModel.cpp.i

.PHONY : src/LinearModel.i

# target to preprocess a source file
src/LinearModel.cpp.i:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/LinearModel.cpp.i
.PHONY : src/LinearModel.cpp.i

src/LinearModel.s: src/LinearModel.cpp.s

.PHONY : src/LinearModel.s

# target to generate assembly for a file
src/LinearModel.cpp.s:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/LinearModel.cpp.s
.PHONY : src/LinearModel.cpp.s

src/Params.o: src/Params.cpp.o

.PHONY : src/Params.o

# target to build an object file
src/Params.cpp.o:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/Params.cpp.o
.PHONY : src/Params.cpp.o

src/Params.i: src/Params.cpp.i

.PHONY : src/Params.i

# target to preprocess a source file
src/Params.cpp.i:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/Params.cpp.i
.PHONY : src/Params.cpp.i

src/Params.s: src/Params.cpp.s

.PHONY : src/Params.s

# target to generate assembly for a file
src/Params.cpp.s:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/Params.cpp.s
.PHONY : src/Params.cpp.s

src/SGDLearner.o: src/SGDLearner.cpp.o

.PHONY : src/SGDLearner.o

# target to build an object file
src/SGDLearner.cpp.o:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SGDLearner.cpp.o
.PHONY : src/SGDLearner.cpp.o

src/SGDLearner.i: src/SGDLearner.cpp.i

.PHONY : src/SGDLearner.i

# target to preprocess a source file
src/SGDLearner.cpp.i:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SGDLearner.cpp.i
.PHONY : src/SGDLearner.cpp.i

src/SGDLearner.s: src/SGDLearner.cpp.s

.PHONY : src/SGDLearner.s

# target to generate assembly for a file
src/SGDLearner.cpp.s:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SGDLearner.cpp.s
.PHONY : src/SGDLearner.cpp.s

src/SVMLightFileFeatureProvider.o: src/SVMLightFileFeatureProvider.cpp.o

.PHONY : src/SVMLightFileFeatureProvider.o

# target to build an object file
src/SVMLightFileFeatureProvider.cpp.o:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SVMLightFileFeatureProvider.cpp.o
.PHONY : src/SVMLightFileFeatureProvider.cpp.o

src/SVMLightFileFeatureProvider.i: src/SVMLightFileFeatureProvider.cpp.i

.PHONY : src/SVMLightFileFeatureProvider.i

# target to preprocess a source file
src/SVMLightFileFeatureProvider.cpp.i:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SVMLightFileFeatureProvider.cpp.i
.PHONY : src/SVMLightFileFeatureProvider.cpp.i

src/SVMLightFileFeatureProvider.s: src/SVMLightFileFeatureProvider.cpp.s

.PHONY : src/SVMLightFileFeatureProvider.s

# target to generate assembly for a file
src/SVMLightFileFeatureProvider.cpp.s:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SVMLightFileFeatureProvider.cpp.s
.PHONY : src/SVMLightFileFeatureProvider.cpp.s

src/SparseVectorN.o: src/SparseVectorN.cpp.o

.PHONY : src/SparseVectorN.o

# target to build an object file
src/SparseVectorN.cpp.o:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SparseVectorN.cpp.o
.PHONY : src/SparseVectorN.cpp.o

src/SparseVectorN.i: src/SparseVectorN.cpp.i

.PHONY : src/SparseVectorN.i

# target to preprocess a source file
src/SparseVectorN.cpp.i:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SparseVectorN.cpp.i
.PHONY : src/SparseVectorN.cpp.i

src/SparseVectorN.s: src/SparseVectorN.cpp.s

.PHONY : src/SparseVectorN.s

# target to generate assembly for a file
src/SparseVectorN.cpp.s:
	$(MAKE) -f CMakeFiles/sgdtk.dir/build.make CMakeFiles/sgdtk.dir/src/SparseVectorN.cpp.s
.PHONY : src/SparseVectorN.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Train"
	@echo "... sgdtk"
	@echo "... Train.o"
	@echo "... Train.i"
	@echo "... Train.s"
	@echo "... src/DenseVectorN.o"
	@echo "... src/DenseVectorN.i"
	@echo "... src/DenseVectorN.s"
	@echo "... src/Exception.o"
	@echo "... src/Exception.i"
	@echo "... src/Exception.s"
	@echo "... src/LinearModel.o"
	@echo "... src/LinearModel.i"
	@echo "... src/LinearModel.s"
	@echo "... src/Params.o"
	@echo "... src/Params.i"
	@echo "... src/Params.s"
	@echo "... src/SGDLearner.o"
	@echo "... src/SGDLearner.i"
	@echo "... src/SGDLearner.s"
	@echo "... src/SVMLightFileFeatureProvider.o"
	@echo "... src/SVMLightFileFeatureProvider.i"
	@echo "... src/SVMLightFileFeatureProvider.s"
	@echo "... src/SparseVectorN.o"
	@echo "... src/SparseVectorN.i"
	@echo "... src/SparseVectorN.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

